require("custom.modules.mode_number_color")
require("custom.modules.eof_padding")
require("custom.modules.code_runner")
require("custom.modules.indent_guides")
require("custom.modules.window_swapper")
require("custom.modules.winbar_breadcrumbs")
